name: CI

on:
  workflow_call:
    inputs:
      apt_packages:
        description: Additional apt packages to install on Ubuntu
        type: string
        default: ""

      check_args:
        type: string
        default: ""

      clippy_args:
        type: string
        default: ""

      test_args:
        type: string
        default: ""

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - uses: swatinem/rust-cache@v2
      - run: cargo check ${{ inputs.check_args }}

  fmt:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: swatinem/rust-cache@v2
      - run: cargo clippy --all-targets -- -D warnings ${{ inputs.clippy_args }}

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install Linux Dependencies
        if: inputs.apt_packages != ''
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ inputs.apt_packages }}
      - uses: dtolnay/rust-toolchain@stable
      - uses: swatinem/rust-cache@v2
      - run: cargo test ${{ inputs.test_args }}
